# Learning how to use numpy

Following along with this guide: [numpy quickstart](https://numpy.org/devdocs/user/quickstart.html)

In [1]:
import numpy as np


# make a 2-d array, 
# from 0 - 14,
# with 3 rows and 5 columns
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
# make simple array, must be an iterable
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [3]:
# make 2-d array with complex numbers
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [4]:
# make different types of initalized arrays
np.zeros((3, 4)) # 3 rows, 4 columns, all zero
np.ones((2,3,4), dtype=np.int16) # 3-d array, 3 rows, 4 columns, all # 1
np.empty((2,3), dtype=np.float64) # random numbers

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [7]:
# making arrays with range
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [8]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Basic Operations

Basic arthimetic operations on arrays apply _elementwise_. A new array is created and filled with results

In [11]:
a = np.arange(20, 60, 10)
b = np.arange(4)
c = a - b # subtract by element i.e. 20 - 0, 30 - 1, ...
c

array([20, 29, 38, 47])

In [12]:
b**2

array([0, 1, 4, 9])

In [15]:
a < 35 # test condition on ALL array elements

array([ True,  True, False, False])

In [16]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

A * B # per element product

array([[2, 0],
       [0, 4]])

In [17]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [18]:
A.dot(B) # same thing

array([[5, 4],
       [3, 4]])

## Modify existing arrays

To modify existing arrays, use the operator equals ( `+=` ) symbol to modify arrays in place, instead of creating a new one. 

In [19]:
rg = np.random.default_rng(1) # make default rng with seed of 1
a = np.ones((2, 3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [20]:
b += a
b  #  b types will be used, because they are "more precise", float64?

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [21]:
# Many unary operators are methods on the array
a.sum()
a.min

<function ndarray.min>

In [23]:
# Many unary operators are implemented as methods on ndarray
a = rg.random((2,3))
(a.sum(), a.min(), a.max())

(3.1057109529998157, 0.027559113243068367, 0.8277025938204418)

In [ ]:
left off at universal functions